# Generated by Django 2.2.2 on 2019-06-04 03:51

import Scores.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('min_bpm', models.IntegerField()),
                ('max_bpm', models.IntegerField(null=True)),
                ('beg', models.IntegerField(null=True)),
                ('bsp', models.IntegerField(null=True)),
                ('dsp', models.IntegerField(null=True)),
                ('esp', models.IntegerField(null=True)),
                ('csp', models.IntegerField(null=True)),
                ('bdp', models.IntegerField(null=True)),
                ('ddp', models.IntegerField(null=True)),
                ('edp', models.IntegerField(null=True)),
                ('cdp', models.IntegerField(null=True)),
                ('beg_steps', models.IntegerField(default=0)),
                ('bsp_steps', models.IntegerField(default=0)),
                ('dsp_steps', models.IntegerField(default=0)),
                ('esp_steps', models.IntegerField(default=0)),
                ('csp_steps', models.IntegerField(default=0)),
                ('bdp_steps', models.IntegerField(default=0)),
                ('ddp_steps', models.IntegerField(default=0)),
                ('edp_steps', models.IntegerField(default=0)),
                ('cdp_steps', models.IntegerField(default=0)),
                ('beg_holds', models.IntegerField(default=0)),
                ('bsp_holds', models.IntegerField(default=0)),
                ('dsp_holds', models.IntegerField(default=0)),
                ('esp_holds', models.IntegerField(default=0)),
                ('csp_holds', models.IntegerField(default=0)),
                ('bdp_holds', models.IntegerField(default=0)),
                ('ddp_holds', models.IntegerField(default=0)),
                ('edp_holds', models.IntegerField(default=0)),
                ('cdp_holds', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('1', 'BEG'), ('2', 'BSP'), ('3', 'DSP'), ('4', 'ESP'), ('5', 'CSP'), ('6', 'BDP'), ('7', 'DDP'), ('8', 'EDP')], default=1, max_length=1)),
                ('marvelous', models.IntegerField()),
                ('perfect', models.IntegerField()),
                ('great', models.IntegerField()),
                ('good', models.IntegerField()),
                ('OK', models.IntegerField()),
                ('miss', models.IntegerField()),
                ('proof', models.ImageField(upload_to=Scores.models.user_directory_path)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Profile')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scores.Song')),
            ],
        ),
    ]
