# Generated by Django 2.1.5 on 2019-03-05 04:20

import django.db.models.deletion
from django.db import migrations, models

import Accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_rank', models.CharField(
                    choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')],
                    max_length=3)),
                ('max_combo', models.IntegerField()),
                ('marvelous', models.IntegerField()),
                ('perfect', models.IntegerField()),
                ('great', models.IntegerField()),
                ('good', models.IntegerField()),
                ('OK', models.IntegerField()),
                ('miss', models.IntegerField()),
                ('proof', models.ImageField(upload_to=Accounts.models.user_directory_path)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('bpm', models.IntegerField()),
                ('difficulty', models.CharField(
                    choices=[('B', 'BEGINNER'), ('L', 'LIGHT'), ('D', 'DIFFICULT'), ('E', 'EXPERT'),
                             ('C', 'CHALLENGE')], max_length=1)),
                ('rating', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scores.Mix')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scores.Song'),
        ),
    ]
