# Generated by Django 2.1.5 on 2019-01-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Scores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='ex',
        ),
        migrations.AddField(
            model_name='score',
            name='OK',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='good',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='great',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='marvelous',
            field=models.IntegerField(default=540),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='max_combo',
            field=models.IntegerField(default=840),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='miss',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='perfect',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
