# Generated by Django 2.2 on 2019-04-14 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Scores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField(help_text='Street, City, State, Zip Code, Country, Planet.', max_length=5000)),
                ('rules', models.TextField(help_text='Detail all of the rules of your League here.', max_length=10000)),
                ('competition_date', models.DateField(default=django.utils.timezone.now)),
                ('mix', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Scores.Mix')),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='League.League')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_place', to='Accounts.Profile')),
                ('third', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='third_place', to='Accounts.Profile')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to='Accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('M', 'Master'), ('U', 'Upper Expert'), ('L', 'Lower Expert'), ('N', 'Novice')], max_length=1)),
                ('entrants', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrant', to='Accounts.Profile')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='League.League')),
            ],
            managers=[
                ('tourneys', django.db.models.manager.Manager()),
            ],
        ),
    ]
