# Generated by Django 2.2.2 on 2019-06-04 03:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0001_initial'),
        ('Scores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rules', models.TextField(help_text='Detail all of the rules of your League here.', max_length=10000)),
                ('competition_date_start', models.DateField(default=datetime.datetime.now)),
                ('competition_date_end', models.DateField(default=datetime.datetime.now)),
                ('mix', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Scores.Mix')),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
                ('division', models.CharField(choices=[('M', 'Master'), ('U', 'Upper Expert'), ('L', 'Lower Expert'), ('N', 'Novice')], max_length=1)),
                ('art', models.ImageField(blank=True, null=True, upload_to='images/trial_art')),
                ('song1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_song', to='Scores.Song')),
                ('song2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_song', to='Scores.Song')),
                ('song3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_song', to='Scores.Song')),
                ('song4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_song', to='Scores.Song')),
            ],
        ),
        migrations.CreateModel(
            name='TrialEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to='Accounts.Profile')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='League.Trial')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='League.League')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_place', to='Accounts.Profile')),
                ('third', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='third_place', to='Accounts.Profile')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to='Accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('M', 'Master'), ('U', 'Upper Expert'), ('L', 'Lower Expert'), ('N', 'Novice')], max_length=1)),
                ('entrants', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrant', to='Accounts.Profile')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='League.League')),
            ],
            managers=[
                ('federation', django.db.models.manager.Manager()),
            ],
        ),
    ]
