# Generated by Django 2.1.5 on 2019-01-06 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('NB', 'Non-Binary'), ['M', 'Male'], ('F', 'Female')], default='NB', max_length=2)),
                ('DOB', models.DateField()),
                ('bio', models.TextField(max_length=5000)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
