# Generated by Django 2.1.5 on 2019-01-08 04:07

from django.db import migrations, models

import Accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ('Accounts', '0002_remove_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='assets/default.jpg', upload_to=Accounts.models.user_directory_path),
        ),
    ]
