# Generated by Django 2.1.5 on 2019-01-09 02:08

import datetime

from django.db import migrations, models

import Accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ('Accounts', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default=datetime.date(1984, 5, 18)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to=Accounts.models.user_directory_path),
        ),
    ]
