# Generated by Django 2.1.5 on 2019-01-10 03:20

from django.db import migrations, models

import Accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ('Accounts', '0004_auto_20190108_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rival_code',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(blank=True, help_text='When were you born?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', help_text='Show your face, if you would.',
                                    upload_to=Accounts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tagline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
