# Generated by Django 2.1.7 on 2019-03-05 03:05

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('Scores', '0001_initial'),
        ('Accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('place1', models.IntegerField()),
                ('place2', models.IntegerField()),
                ('place3', models.IntegerField()),
                ('place4', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location',
                 models.TextField(help_text='Street, City, State, Zip Code, Country, Planet.', max_length=5000)),
                ('rules',
                 models.TextField(help_text='Detail all of the rules of your tournament here.', max_length=10000)),
                ('comp_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mix', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Scores.Mix')),
                ('organizer',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prize_Pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tourney.Prize')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('M', 'Master'), ('U', 'Upper Expert'), ('L', 'Lower Expert')],
                                              max_length=1)),
                ('entrants', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrant',
                                               to='Accounts.Profile')),
                ('tourney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tourney.Tournament')),
            ],
            managers=[
                ('tourneys', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_place',
                                   to='Accounts.Profile')),
                ('third', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='third_place',
                                            to='Accounts.Profile')),
                ('tourney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tourney.Tournament')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner',
                                             to='Accounts.Profile')),
            ],
        ),
    ]
