# Generated by Django 2.1.7 on 2019-03-05 03:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Tourney', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='comp_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='prize_Pool',
        ),
        migrations.AddField(
            model_name='tournament',
            name='competition_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Prize',
        ),
    ]
